# Meta Data for SEO

## Homepage
title = "TweetNFTs"
titleSeparator = "|"
titleAddition = "Tweet it. Mint it."
description = "Collect, back up, and mint your favorite tweets as NFTs."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["tweetnfts.png"]
ogLocale = "en_US"
domainTLD = "tweetnfts.xyz"
titleHome = "TweetNFTs"

## Twitter Cards
twitterSite = "@tweetnfts"
twitterCreator = "@tweetnfts"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "TweetNFTs"
schemaLocale = "en-US"
schemaLogo = "logo-tweetnfts.png"
schemaLogoWidth = 500
schemaLogoHeight = 500
schemaImage = "tweetnfts.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/tweetnfts"
schemaGitHub = "https://github.com/tweetnfts"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "tweetnfts.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "<p style='font-size: 80%'>Made with 💙 by <a href='https://twitter.com/Thomas181197'>Thomas</a> and <a href='https://twitter.com/maxdesalle'>Maxime</a>, with help from <a href='https://www.linkedin.com/in/guillaume-wafflard/'>Guillaume</a>, <a href='https://www.linkedin.com/in/omar-g-69892a119/'>Omar</a> and Baktash</p>"

# Feed
copyRight = "Copyright (c) 2023 TweetNFTs"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
